name: "JS Tests"

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - "src/**"

jobs:
  yarn-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.node-version }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn test
